server:
  port: 8083
  servlet:
    context-path: /member

spring:
  #MySQL数据源
#  datasource:
#    username: #{spring.datasource.username}
#    password: #{spring.datasource.password}
#    url: #{spring.datasource.url}
#    driver-class-name: #{spring.datasource.driver-class-name}

  application:
    name: member
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    #zookeeper配置中心
    zookeeper:
      connect-string: 203.195.246.36:2181,203.195.246.36:2182,203.195.246.36:2183
      discovery:
        enabled: true
        register: true

#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.himoko.member.pojo
  configuration:
    #自动转化成驼峰
    map-underscore-to-camel-case: true
