server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8081/api
          predicates:
            - Path=/member/**
            - Method=GET
