server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: api
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    #zookeeper≈‰÷√÷––ƒ
    zookeeper:
      connect-string: 203.195.246.36:2181,203.195.246.36:2182,203.195.246.36:2183
      discovery:
        enabled: true
        register: true
